version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      # Traefik console
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/static.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      - frontend

networks:
  frontend:
    external: true
