http:
  routers:
    traefik:
      rule: "Host(`traefik.docker`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker"
            sans:
              - "*.docker"
          - main: "local.itkdev.dk"
            sans:
              - "*.local.itkdev.dk"
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
